---
# Labels names are important as they are used by Release Drafter to decide
# regarding where to record them in changelog or if to skip them.
#
# The repository labels will be automatically configured using this file and
# the GitHub Action https://github.com/marketplace/actions/github-labeler.
- name: "Bug: Confirmed!"
  description: Something isn't working
  color: d73a4a
- name: "Bug: False Alarm"
  description: no Bug - False Alarm
  color: 80006C
- name: check for Bug
  description: it is checked whether there is an Bug
  color: 1AFF00
- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca
- name: duplicate
  description: This issue or pull request already exists
  color: cfd3d7
- name: feature request
  description: Request a new Xplora® Watch feature
  color: a2eeef
- name: help wanted
  description: Extra attention is needed
  color: 008672
- name: invalid
  description: This doesn't seem right
  color: e4e669
- name: performance
  description: Performance
  color: "016175"
- name: question
  description: Further information is requested
  color: d876e3
- name: Configuration incorrect
  description: Configuration implemented incorrectly
  color: 8AFF00
- name: "A: Country Code"
  description: add Country Code
  color: "0000FF"
- name: "R: Country Code"
  description: remove Country Code
  color: "FF00FF"
