name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
categories:
  - title: 'New'
    label: 'feature request'
  - title: 'Bug Fixes'
    label: 'Fix Bug'
  - title: 'Documentation'
    label: 'documentation'
    collapse-after: 5

version-resolver:
  minor:
    labels:
      - 'feature request'
  patch:
    labels:
      - 'Fix Bug'
      - 'documentation'

exclude-labels:
  - 'skip-changelog'