ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        args:
          - --fix
          - --line-length=127
        exclude: custom_components/xplora_watch/geocoder.py
      - id: ruff-format
        files: ^((custom_components|scripts|tests)/.+)?[^/]+\.py$
        exclude: custom_components/xplora_watch/geocoder.py
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=additionals,alle,alot,bund,currenty,datas,deine,farenheit,falsy,fo,haa,hass,iif,incomfort,ines,intoto,ist,manuell,nam,nd,pres,pullrequests,resset,rime,ser,serie,te,technik,ue,unsecure,withing,zar
          - --skip="./.*,*.csv,*.json,*.ambr"
          - --quiet-level=2
        exclude_types: [csv, json]
        exclude: custom_components/xplora_watch/geocoder.py
        additional_dependencies:
          - tomli
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        exclude: (.vscode|.devcontainer)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude_types: [json]
        exclude: (markdown-card-read-messages\.md)
  - repo: https://github.com/cdce8p/python-typing-update
    rev: v0.7.0
    hooks:
      # Run `python-typing-update` hook manually from time to time
      # to update python typing syntax.
      # Will require manual work, before submitting changes!
      # pre-commit run --hook-stage manual python-typing-update --all-files
      - id: python-typing-update
        stages: [manual]
        args:
          - --py312-plus
          - --force
          - --keep-updates
        files: ^(custom_components|tests|scripts)/.+\.py$
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.1
    hooks:
      - id: gitleaks
  # - repo: https://github.com/pylint-dev/pylint
  #   rev: v3.3.3
  #   hooks:
  #     - id: pylint
