send_message:
  name: Send message
  description: Send message to target Watch
  fields:
    message:
      name: Message
      description: The message to be sent.
      required: true
      example: This is a message I am sending to Watch
      selector:
        text:
    target:
      name: Target
      description:
        An array of targets to send the notification to.
      example: 1234567890
      selector:
        object:

toggle:
  name: Xplora Tracker Switch
  description: Toggle an input boolean
  target:
    entity:
      domain: input_boolean