---
name: "Bug"
description: You use this when something is not doing what it's supposed to do.
labels: "check for Bug"
body:
- type: markdown
  attributes:
    value: |
      Before you open a new issue, search through the existing issues to see if others have had the same problem.
- type: textarea
  attributes:
    label: "System Health details"
    description: "Paste the data from the System Health card in Home Assistant (https://www.home-assistant.io//more-info/system-health#github-issues)"
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have enabled debug logging for my installation.
        required: true
      - label: This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
        required: true
- type: textarea
  attributes:
    label: "Describe the issue"
    description: "A clear and concise description of what the issue is."
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction steps
    description: "Without steps to reproduce, it will be hard to fix, it is very important that you fill out this part, issues without it will be closed"
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  attributes:
    label: "Debug logs"
    description: "To enable debug logs check this https://github.com/Ludy87/xplora_watch#debug"
    render: text
  validations:
    required: true
