blank_issues_enabled: false
contact_links:
  - name: 💸 Want to donate?
    url: https://www.buymeacoffee.com/ludy87
    about: I like coffee
  - name: Wish list
    url: https://smile.amazon.de/registry/wishlist/2MX8QK8VE9MV1
    about: Thanks
