name: Remove Country Code
description: Remove Country Code
title: "[🏳 remove Country Code] (Country summary)"
labels: 'R: Country Code'
body:
  - type: input
    attributes:
      label: Country Name
      description: Specify the country to remove in the documentation.
      placeholder: Germany
    validations:
      required: true
  - type: input
    attributes:
      label: Country Code
      description: Specify the country code to remove in the documentation.
      placeholder: 49 or +49
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Correctness
      description: My details are correct and have been checked by me.
      options:
        - label: I agree that everything is correct.
          required: true
