name: Buy Me A Coffee Readme

on:
    push:
      branches: [main]
    workflow_dispatch:
    schedule:
        # Runs at every 12AM UTC
        - cron: "0 0 * * *"

jobs:
  bmac-readme:
    name: Update Buy Me A Coffee section in this repo's README
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
        - run: ls -la
          shell: bash
        - uses: akosbalasko/coffee-to-file@1.0.1
          with:
            BUY_ME_A_COFFEE_TOKEN: ${{ secrets.BUY_ME_A_COFFEE_TOKEN }}
            NUMBER_OF_MESSAGES: 50
            FILENAME: "README.md"

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v5.0.2
          with:
            token: ${{ secrets.TOKEN }}
            commit-message: Buy me a Coffee messages updated
            signoff: true
            base: main
            title: Buy Me a Coffee Readme action
            body: |
              Buy me a Coffee messages updated
              
              Auto-generated by [create-pull-request][1]
      
              [1]: https://github.com/peter-evans/create-pull-request
            labels: |
                wait
                in progress
                bot
