name: Buy Me A Coffee Readme

on:
    push:
      branches: [main]
    workflow_dispatch:
    schedule:
        # Runs at every 12AM UTC
        - cron: "0 0 * * *"

jobs:
  bmac-readme:
    name: Update Buy Me A Coffee section in this repo's README
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
        - run: ls -la
          shell: bash
        - uses: akosbalasko/coffee-to-file@1.0.1
          with:
            BUY_ME_A_COFFEE_TOKEN: ${{ secrets.BUY_ME_A_COFFEE_TOKEN }}
            NUMBER_OF_MESSAGES: 50
            FILENAME: "README.md"
        - uses: stefanzweifel/git-auto-commit-action@v4.16.0
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
          with:
            file_pattern: README.md
            commit_message: Buy me a Coffee messages updated
            branch: main
            commit_user_name: Buy Me a Coffee Readme action
            commit_user_email: noreply@buymeacoffeereadmeaction.com
