name: Buy Me A Coffee Readme

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
      # Runs at every 12AM UTC
      - cron: "0 0 * * *"

jobs:
  bmac-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Update Buy Me A Coffee section in this repo's README
    steps:
      - uses: Ludy87/action/coffee-readme@main
        with:
          BUY_ME_A_COFFEE_TOKEN: ${{ secrets.BUY_ME_A_COFFEE_TOKEN }}
          BRANCH: coffee
