name: Dynamic Template

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
        with:
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.9'
      - name: Install dependencies
        env:
          PHONENUMBER: ${{ secrets.PHONENUMBER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python -m pip install --upgrade pip
          pip install pyxplora_api==1.0.24 -U
          python ./.github/actions/update_readme.py
      - name: "💾 Github Repository Metadata"
        uses: varunsridharan/action-repository-meta@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: "💫 Dynamic Template Render"
        uses: varunsridharan/action-dynamic-readme@main
        with:
          GLOBAL_TEMPLATE_REPOSITORY: Ludy87/xplora_watch
          files: |
            README.md
          confirm_and_push: false # Important if use "Require a pull request before merging" rule
        env:
          PHONENUMBER: ${{ secrets.PHONENUMBER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          file_pattern: README.md
          commit_message: 📝 Update generated README
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
