name: "Flake check"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate_flake8:
    name: "flake8"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --ignore=E501,E266,E202,E201,E301
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=30 --max-line-length=127 --statistics --ignore=E501,E266,E202,E201,E301
      - name: Check for fatal errors
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Docstrings
        run: |
          flake8 . --count --exit-zero --max-complexity=30 --max-line-length=127 --statistics --select=D,DAR
      - name: Small tweaks that might help, but might conflict or be inconvenient
        run: |
          flake8 . --count --exit-zero --max-complexity=30 --max-line-length=127 --statistics --select=WPS323,WPS336,WPS305,WPS420,WPS440,WPS441,WPS515,E800\:,WPS421,W503,WPS412
      - name: Trailing commas and isort
        run: |
          flake8 . --count --exit-zero --max-complexity=30 --max-line-length=127 --statistics --select=I,C81
      - name: Overcomplex code
        run: |
          flake8 . --count --exit-zero --max-complexity=30 --max-line-length=127 --statistics --select=WPS201,WPS210,WPS214,WPS221,WPS229,WPS226
      - name: Useless stuff
        run: |
          flake8 . --count --exit-zero --max-complexity=30 --max-line-length=127 --statistics --select=F401,F841,WPS327,WPS503,WPS504,WPS507
      - name: Bandit
        run: |
          flake8 . --count --exit-zero --max-complexity=30 --max-line-length=127 --statistics --select=S
      - name: Clarity and quality improvements
        run: |
          flake8 . --count --exit-zero --max-complexity=30 --max-line-length=127 --statistics --select=WPS432,WPS110,WPS111,WPS322,E501
      - name: General stats
        run: |
          flake8 . --count --exit-zero --max-complexity=30 --max-line-length=127 --statistics \
            --ignore=D,DAR,WPS323,WPS336,WPS305,WPS420,WPS440,WPS441,WPS515,E800\:,WPS421,W503,WPS412,I,C81,WPS201,WPS210,WPS214,WPS221,WPS229,WPS226,F401,F841,WPS327,WPS503,WPS504,WPS507,S,WPS432,WPS110,WPS111,WPS322,E501
