name: Manage labels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  labeler:
    name: Labeler
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.5.0

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4.1.0
        with:
          github-token: ${{ secrets.TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: true