name: Issue Auto close

on:
  issues:
    types: [opened]

jobs:
  titlePrefixCheck:
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.event.issue.title, 'Logout') == 'true'
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            # Workaround for logout in the Xplora® App

            1. add phone number from watch to contacts (as admin)
            2. create a login profile for this phone number
            3. log into the app with the created profile to test whether it works
            4. use the login data for the integration
