name: Issue Auto close

on:
  issues:
    types: [opened]

jobs:
  titlePrefixCheck:
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.event.issue.title, 'Logout') || contains(github.event.issue.title, 'app')
        name: Close Issue
        uses: peter-evans/close-issue@v3.0.1
        with:
          comment: |
            [# Workaround for logout in the Xplora® App](https://github.com/Ludy87/xplora_watch/issues/24)

            This action was performed automatically.
