name: Set Labels on Pull Request

on:
  pull_request:
    types:
      - closed
      - reopened

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: write
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Check if Pull Request
        id: check_pr
        run: echo "is_pull_request=${{ github.event_name == 'pull_request' }}" >> $GITHUB_ENV
      - if: env.is_pull_request == 'true'
        name: Merge
        uses: Ludy87/action/merge@v1.0.7
