name: Set Labels on Pull Request

on:
  pull_request:
    types:
      - closed
      - reopened

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check if Pull Request
        id: check_pr
        run: echo "is_pull_request=${{ github.event_name == 'pull_request' }}" >> $GITHUB_ENV
      - if: env.is_pull_request == 'true'
        name: Merge
        uses: Ludy87/action/merge@d5cd9da51b4f77739b9b399d5a855b26905c3143 # v1.0.7
