name: Release Version

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0
        with:
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v4.4.0
        with:
          python-version: '3.9'
          check-latest: true
      - name: Install dependencies
        env:
          PHONENUMBER: ${{ secrets.PHONENUMBER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python -m pip install --upgrade pip
          pip install pyxplora_api==1.0.24 -U
          python ./.github/actions/update_readme.py
      - name: Get Version
        id: version
        shell: bash
        run: |
          version="$(python3 ./.github/actions/get_version.py)"
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Is Tag exists
        uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with: 
          tag: ${{ steps.version.outputs.version }}
        # env:
        #   GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - if: steps.checkTag.outputs.exists == 'false'
        name: Check Tagname
        id: check-tag
        run: |
          if [[ "${{ steps.version.outputs.version }}" =~ ^v2\.[0-9]+\.[0-9]+$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi
      - name: Build
        if: steps.check-tag.outputs.match == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          token: "${{ secrets.TOKEN }}"
