name: Release Version

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.0
        with:
          ref: main
      - name: Set up Python 3
        uses: actions/setup-python@v4.7.0
        with:
          python-version: |
            3.11
          check-latest: true
      - name: Install dependencies
        env:
          PHONENUMBER: ${{ secrets.PHONENUMBER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python -m pip install --upgrade pip
          pip install pyxplora_api==1.0.24 -U
          python ./.github/actions/update_readme.py
      - name: Get Version
        id: version
        shell: bash
        run: |
          version="$(python3 ./.github/actions/get_version.py)"
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Is Tag exists
        uses: mukunku/tag-exists-action@v1.4.0
        id: checkTag
        with:
          tag: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: ZIP Component Dir
        if: steps.checkTag.outputs.exists == 'false'
        run: |
          cd ${{ github.workspace }}/custom_components/xplora_watch
          zip -r xplora_watch.zip ./
      - name: Upload zip to release
        if: steps.checkTag.outputs.exists == 'false'
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/xplora_watch/xplora_watch.zip
          asset_name: xplora_watch.zip
          tag: ${{ steps.version.outputs.version }}
          overwrite: true
