name: Daily Update

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: Ludy87/action/update_hacs_hassio@v1.0.3
